remote_theme: just-the-docs/just-the-docs

title: Prefeitura de João Pessoa

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

footer_content: "Copyright 2022 - 2022.1-Interação Humano-Computador - Grupo 4 <a href=\"https://github.com/Interacao-Humano-Computador/2022.1-Prefeitura_Joao_Pessoa\">MIT license.</a>"


# logo: "/assets/logos/logo.png"

aux_links:
  "View on GitHub":
    - "https://github.com/Interacao-Humano-Computador/2022.1-Prefeitura_Joao_Pessoa"
